language: go
go:
  - 1.11.13
  - 1.12.17
  - 1.13.15
  - 1.14.15
  - 1.15.11
  - 1.16.3
  - tip
install:
  - go mod download
script:
  - test -z "$(golint ./... | tee /dev/stderr)"
  - go vet .
  - go test -v .
  - go test -v -bench . -benchmem
jobs:
  allow_failures:
    - go: tip
