language: go
go:
  - 1.11.13
  - 1.12.17
  - 1.13.15
  - 1.14.15
  - 1.15.11
  - 1.16.3
  - tip
install:
  - go get github.com/golang/lint/golint
  - gom -test install
script:
  - test -z "$(golint ./... | tee /dev/stderr)"
  - gom test -v ./...
  - gom test -v -bench .
jobs:
  allow_failures:
    - go: tip
